const signedRelease = process.env.INTERLUDE_SIGNED_RELEASE === '1';
module.exports = {
  appId: 'com.skinnyfatboy05.interlude', productName: 'Interlude',
  directories: { output: 'artifacts/desktop', buildResources: '.desktop-build' },
  files: ['desktop/bootstrap.cjs', 'desktop/main.mjs', 'desktop/preload.cjs', 'desktop/policy.mjs', 'src/**', 'web/**',
    'scripts/build-windows.mjs', 'scripts/build-macos.mjs', 'scripts/native-build.mjs', 'scripts/install-hooks.mjs',
    'package.json', 'PRIVACY.md', 'SECURITY.md'],
  extraResources: [
    { from: '.desktop-build/native', to: 'native' },
    { from: '.desktop-build/icon.png', to: 'icon.png' },
    { from: '.', to: 'companion', filter: ['src/config.mjs', 'src/events.mjs', 'scripts/hook.mjs', 'extension/**'] },
  ],
  asar: true, npmRebuild: false,
  electronFuses: { runAsNode: true, enableNodeOptionsEnvironmentVariable: false, enableNodeCliInspectArguments: false,
    enableEmbeddedAsarIntegrityValidation: true, onlyLoadAppFromAsar: true },
  artifactName: 'Interlude-${version}-${os}-${arch}.${ext}',
  win: { target: ['nsis'], icon: '.desktop-build/icon.png' },
  nsis: { oneClick: false, perMachine: false, allowElevation: false, allowToChangeInstallationDirectory: true,
    createDesktopShortcut: true, include: 'desktop/installer.nsh', deleteAppDataOnUninstall: false },
  mac: { target: ['dmg', 'zip'], icon: '.desktop-build/icon.png', category: 'public.app-category.productivity', minimumSystemVersion: '13.0',
    identity: signedRelease ? undefined : '-', hardenedRuntime: signedRelease,
    notarize: signedRelease ? undefined : false,
    entitlements: 'desktop/entitlements.mac.plist', entitlementsInherit: 'desktop/entitlements.mac.plist',
    binaries: ['Contents/Resources/native/InterludeFocus'] },
  dmg: { sign: true },
  publish: null,
};
